//! Architecture-parity test for the FAN `ConvBlock` port.
//!
//! Uses the tiny committed fixture `convblock_small.safetensors` (random 6→8
//! block, generated by `reference/gen_fixtures.py` from the reference PyTorch
//! `ConvBlock`) so this runs in CI with no model download. Asserts the candle
//! port reproduces the PyTorch output within tight tolerance — validating the
//! trickiest logic (BN eval, three conv branches, concat, downsample residual).

mod common;

use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use vrchat_camera_osc::tracking::fan::model::ConvBlock;

#[test]
fn convblock_matches_pytorch() {
    let device = Device::Cpu;
    let meta: serde_json::Value =
        serde_json::from_slice(&std::fs::read(common::fixture("convblock_small.json")).unwrap())
            .unwrap();
    let in_shape: Vec<usize> = meta["in_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    let out_shape: Vec<usize> = meta["out_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let input = common::read_f32(&common::fixture("convblock_small_input.f32"));
    let expected = common::read_f32(&common::fixture("convblock_small_output.f32"));

    let x = Tensor::from_vec(
        input,
        (in_shape[0], in_shape[1], in_shape[2], in_shape[3]),
        &device,
    )
    .unwrap();

    let vb = unsafe {
        VarBuilder::from_mmaped_safetensors(
            &[common::fixture("convblock_small.safetensors")],
            DType::F32,
            &device,
        )
        .unwrap()
    };
    let block = ConvBlock::new(in_shape[1], out_shape[1], vb).unwrap();
    let y = block.forward(&x).unwrap();

    assert_eq!(y.dims(), out_shape.as_slice(), "output shape mismatch");
    let got = y.flatten_all().unwrap().to_vec1::<f32>().unwrap();

    let max = common::max_abs_diff(&got, &expected);
    let mean = common::mean_abs_diff(&got, &expected);
    eprintln!("ConvBlock parity: max_abs_diff={max:.3e} mean_abs_diff={mean:.3e}");
    assert!(max < 1e-4, "ConvBlock max abs diff {max} exceeds 1e-4");
}
